#ifndef INDETTRACKSELECTIONTOOL_INDETTRACKSELECTIONTOOLDICT_H
#define INDETTRACKSELECTIONTOOL_INDETTRACKSELECTIONTOOLDICT_H

#if defined(__GCCXML__) and not defined(EIGEN_DONT_VECTORIZE)
#define EIGEN_DONT_VECTORIZE
#endif // __GCCXML__

#include "InDetTrackSelectionTool/InDetTrackSelectionTool.h"

#endif // not INDETTRACKSELECTIONTOOL_INDETTRACKSELECTIONTOOLDICT_H
